
# Site settings
title: Journals of a Value Investor
email: hyqi.work@gmail.com
description: This site was moved to https://theoria137.substack.com/, where you can comment and subscribe.
baseurl: ""
url: "http://theoria137.github.io"
twitter_username: ""
github_username: "" 

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
