
# Site settings
title: Journals of a Value Investor
email: hyqi.work@gmail.com
description: "Rather than love, than money, than fame, give me truth."
baseurl: ""
url: "http://theoria137.github.io"
twitter_username: ""
github_username: "" 

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
